[project]
name = "assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.13.1",
    "pydantic-ai>=0.7.4",
    "rich>=14.1.0",
    "openai>=1.51.2",
    "python-dotenv>=1.0.1",
]
